# Generated by Django 4.1 on 2023-11-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام\u200cتخصوص')),
                ('amounts', models.IntegerField(blank=True, null=True, verbose_name=' هزینه ماهانه')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام ماشین\u200cآلات')),
                ('amounts', models.IntegerField(blank=True, null=True, verbose_name='بهای کرایه ماهانه')),
            ],
            options={
                'verbose_name': 'ماشین\u200cآلات',
                'verbose_name_plural': 'ماشین\u200cآلات\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_use', models.CharField(blank=True, max_length=250, null=True, verbose_name='مواد و مصالح مصرفی')),
                ('amounts', models.IntegerField(blank=True, null=True, verbose_name=' هزینه تهیه یاخرید')),
            ],
            options={
                'verbose_name': 'مواد و مصالح',
                'verbose_name_plural': 'مواد و مصالح',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=250, null=True, verbose_name='احجام اجراعی')),
                ('typeـoperation', models.CharField(blank=True, max_length=250, null=True, verbose_name='نوع عملیات')),
                ('amounts', models.IntegerField(blank=True, null=True, verbose_name='مقادیر')),
            ],
            options={
                'verbose_name': 'احجام اجرایی پروژه',
                'verbose_name_plural': 'احجام اجرایی پروژها',
            },
        ),
        migrations.CreateModel(
            name='OperationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uint', models.IntegerField(blank=True, null=True, verbose_name='واحد')),
                ('amounts', models.IntegerField(blank=True, null=True, verbose_name='بهای\u200cواحد عملیات اجرای')),
                ('machinery_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinery_names', to='implementation.machinery', verbose_name='نام ماشین\u200cآلات')),
            ],
            options={
                'verbose_name': 'هزینه عملیات اجرایی',
                'verbose_name_plural': 'هزینه\u200cهای عملیات اجرایی ',
            },
        ),
    ]
