# Generated by Django 4.1 on 2023-12-01 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی '),
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی '),
        ),
        migrations.AddField(
            model_name='operationcost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationcost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی '),
        ),
        migrations.AddField(
            model_name='performance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی '),
        ),
        migrations.AlterField(
            model_name='operationcost',
            name='machinery_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام ماشین\u200cآلات'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='group',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='احجام اجرایی'),
        ),
    ]
