# Generated by Django 4.1 on 2023-12-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0002_machinery_created_at_machinery_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی ')),
                ('chapter_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='شماره فصل')),
                ('item_number', models.IntegerField(blank=True, null=True, verbose_name='شماره آيتم')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='شرح')),
                ('unit', models.CharField(blank=True, max_length=250, null=True, verbose_name='واحد')),
                ('amounts', models.IntegerField(blank=True, null=True, verbose_name='بهاي واحد (ریال)')),
            ],
            options={
                'verbose_name': 'فهرست بها',
                'verbose_name_plural': 'فهرست بها ',
            },
        ),
    ]
