# Generated by Django 4.1 on 2024-01-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0005_remove_resourceallocation_amounts_total_work_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceallocation',
            name='Impact_factor',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='machinery',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='material',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='percents_employee',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='percents_machinery',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='percents_material',
        ),
    ]
