# Generated by Django 4.1 on 2024-01-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0007_remove_resourceallocation_amounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceallocation',
            name='total_work_contractors',
        ),
    ]
